version: '3.8'

services:
  library_db:
    image: mysql
    container_name: library_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
    ports:
      - '3306:3306'
    volumes:
      - library_data:/var/lib/mysql

volumes:
  library_data:
